# Generated by Django 5.2.8 on 2025-12-06 16:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motif', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('OUVERT', 'Ouvert'), ('EN_ANALYSE', 'En analyse'), ('RESOLU', 'Résolu'), ('REJETE', 'Rejeté')], default='OUVERT', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to=settings.AUTH_USER_MODEL)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='commandes.commande')),
                ('cuisinier', models.ForeignKey(blank=True, limit_choices_to={'role': 'CUISINIER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_recues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
