# Generated by Django 5.2.8 on 2025-12-08 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_alter_commande_statut'),
        ('plats', '0004_remove_plat_photo_url_plat_photo'),
        ('reclamations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='plat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations', to='plats.plat'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='motif',
            field=models.CharField(choices=[('QUALITE_PLAT', 'Qualité du plat'), ('DELAI', 'Délai de livraison'), ('ERREUR_COMMANDE', 'Erreur dans la commande'), ('AUTRE', 'Autre')], default='AUTRE', max_length=30),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='statut',
            field=models.CharField(choices=[('OUVERT', 'Ouvert'), ('LU', 'Lue par le cuisinier'), ('EN_COURS', 'En cours de traitement'), ('TRAITEE', 'Traitée'), ('REJETEE', 'Rejetée')], default='OUVERT', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='reclamation',
            unique_together={('client', 'commande', 'plat')},
        ),
    ]
