# Generated by Django 5.2.8 on 2025-12-03 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paniers', '0001_initial'),
        ('plats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignepanier',
            name='plat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plats.plat'),
        ),
    ]
