# Generated by Django 5.2.8 on 2025-12-03 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paniers', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='paniers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lignepanier',
            name='panier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='paniers.panier'),
        ),
        migrations.AlterUniqueTogether(
            name='lignepanier',
            unique_together={('panier', 'plat')},
        ),
    ]
