# Generated by Django 5.2.8 on 2025-12-06 16:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('SUCCES', 'Succès'), ('ECHEC', 'Échec'), ('REMBOURSE', 'Remboursé')], default='EN_ATTENTE', max_length=20)),
                ('type', models.CharField(choices=[('CARTE_CREDIT', 'Carte de crédit'), ('CARTE_DEBIT', 'Carte de débit'), ('PAYPAL', 'PayPal'), ('APPLE_PAY', 'Apple Pay')], default='CARTE_CREDIT', max_length=20)),
                ('transaction_ref', models.CharField(blank=True, max_length=255)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='commandes.commande')),
            ],
        ),
    ]
