# Generated by Django 5.2.8 on 2025-12-06 16:29

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plats', '0004_remove_plat_photo_url_plat_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('EN_PREPARATION', 'En cours de préparation'), ('EN_LIVRAISON', 'En cours de livraison'), ('LIVREE', 'Livrée')], default='EN_PREPARATION', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stripe_session_id', models.CharField(blank=True, help_text='ID de la session Stripe Checkout liée à cette commande', max_length=255, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('sous_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='commandes.commande')),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_commandes', to='plats.plat')),
            ],
        ),
    ]
