# Generated by Django 5.2.8 on 2025-12-03 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='avis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plat',
            name='cuisinier',
            field=models.ForeignKey(limit_choices_to={'role': 'CUISINIER'}, on_delete=django.db.models.deletion.CASCADE, related_name='plats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='avis',
            name='plat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='plats.plat'),
        ),
    ]
