# Generated by Django 5.2.8 on 2025-12-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plats', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plat',
            name='adresse',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='plat',
            name='cree_le',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plat',
            name='ville',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
