# Generated by Django 5.2.8 on 2025-12-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plats', '0003_plat_adresse_plat_cree_le_plat_ville'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plat',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='plat',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='plats/'),
        ),
    ]
