# Generated by Django 5.2.8 on 2025-12-08 05:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plats', '0004_remove_plat_photo_url_plat_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.PositiveSmallIntegerField()),
                ('commentaire', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_laisses', to=settings.AUTH_USER_MODEL)),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_clients', to='plats.plat')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('client', 'plat')},
            },
        ),
    ]
